### PR TITLE
Fix build for MSVC.

### PR DESCRIPTION
**Pull request by SergeySeroshtan**
Add missing headers to the 'helpers.hpp'.

### CODE REVIEW

**Comment by anuragsoni** [comment]
Hi @SergeySeroshtan Thanks for the Pull request. What version of MSVC did you compile against? Also maybe it would be a good idea to add a continuous build with appveyor to compile against MSVC?

**Comment by SergeySeroshtan** [comment]
Used toolchain:
- cmake 3.2.2
- nmake of MSVC 2015

**Comment by SergeySeroshtan** [comment]
Add continuous build with appveyor to compile against MSVC is a good idea, but it will take some time due to libcurl dependency.

**Comment by anuragsoni** [comment]
I will merge this Pull Request and I can create an issue about appveyor support so it can be tracked there.

Thanks

**Comment by anuragsoni** [comment]
#1

**Pull request merged**
